= w
:description: Wordlist / glossary / dictionary entry
:url-repo: https://github.com/usfm-bible/tcdocs/blob/main/markers/char/w.adoc
ifndef::localdir[]
:source-highlighter: pygments
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

// tag::public[]

== Summary

Description:: Wordlist / glossary / dictionary entry. Surround a word or phrase with this markup to indicate that it should appear in the glossary.
Syntax::
* *USFM:* `+\w_{content}|[@lemma,strong,srcloc]\w*+`
* *USX:* `+<char style="w" [@lemma,strong,srcloc]>{content}</char>+`
Attributes:::
** `lemma` - Citation form for the term in the glossary _(default)_
** `strong` - Strong’s ID in the form `+H####+` (Hebrew) or `+G####+` (Greek)
*** A strong’s ID augmentation identifier, if required, should be separated from the strong value by a colon `:`. An augmentation is a method of extending Strong’s by aligning it to another lexicon (e.g. Brown-Driver-Briggs). This requires dividing some words into two or more separate words.
*** There are instances where more than one word may need to be included within `+\w_...\w*+` because of how Hebrew and Greek use word repetition - e.g. for a superlative. Exodus 29:37 repeats the word ‘holy’ as the superlative form.
** `srcloc` - Location of the word in the source text; Example: GNT version 5 text, book 51, chapter 1, verse 2, word 1.
// tag::spec[]
Added:: 1.0
Updated:: 3.0 (attributes)
// end::spec[]

== Properties

StyleType:: Character
OccursUnder:: `[BookIntroductionContent], [ChapterContent], [SidebarContent], [FootnoteContent], [PeripheralContent]`
TextType:: VerseText
TextProperties:: publishable, vernacular

== Structure

'Railroad' type diagram here...

== Examples

Source USFM text and corresponding formatted layout image

== Publication Issues

// end::public[]

== Discussion

Links to open repository Issues