
alljobs = {
    "BookHeaders":          ("bkhdrs", ("BookHeaders.para.style.enum",)),
    "BookTitles":           ("bktitles", ("BookTitles.para.style.enum",)),
    "BookIntroduction":     ("bkintro", ('BookIntroduction.para.style.enum',)),
    "BookIntroductionEndTitles": ("bkintroend", ("BookIntroductionEndTitles.para.style.enum",)),
    "ChapterStart":         ("chapter",),
    "ChapterEnd":           ("chapterend",),
    "Char":                 ("char", ("Char.char.style.enum", "+char.closed", "Break",
                                        "CharWithAttrib.enum", "CharContent"), ("+char.link", )),
    "CharEmbed":            ("charembed", ("Char.char.style.enum", "+char.closed", "Break",
                                            "CharEmbedWithAttrib", "CharWithAttrib.enum"), ("+char.link", )),
    "CharWithAttrib":       ("charattrib", ("CharWithAttrib.enum")),
    "CrossReference":       ("crossref",),
    "CrossReferenceChar":   ("xchar",("CrossReferenceChar.char.style.enum", "+char.closed")),
    "Footnote":             ("f", tuple(), ("category", )),
    "FootnoteChar":         ("fchar", ("FootnoteVerse", "FootnoteChar.char.style.enum", "char.closed")),
    "List":                 ("list", ("List.para.style.enum",)),
    "ListChar":             ("listchar", ("+char.closed", "ListChar.char.style.enum",)),
    "Milestone":            ("ms", ("MilestoneWithAttrib.enum", "MilestoneWithAttrib.ms.style.qt")),
    "Para":                 ("p", ("Para.para.style.enum", "Break")),
    "PeripheralDivision":   ("periph", ("Peripheral.FRT.periph.id.enum", "Peripheral.INT.periph.id.enum",
                                        "Peripheral.BAK.periph.id.enum", "Peripheral.OTH.periph.id.enum", "PeripheralContent")),
    "Scripture":            ("id", ("BookIdentification", "BookIdentification.book.code.enum", "ChapterContent")),
    "Sidebar":              ("esb",),
    "Table":                ("table", ("TableContent",)),
    "VerseStart":           ("verse",),
    "VerseEnd":             ("verseend",),
    "category":             ("cat",),
    "char.link":            ("link",),
}

usxenums = {
    'bookidentification': 'BookIdentification.book.code',
    'peripheralbookidentification': 'PeripheralBookIdentification.book.code',
    'periperhaldividedbookidentification': 'PeripheralDividedBookIdentification.book.code',
    'frt': 'Peripheral.FRT.periph.id',
    'int': 'Peripheral.INT.periph.id',
    'bak': 'Peripheral.BAK.periph.id',
    'oth': 'Peripheral.OTH.periph.id',
    'bookheader': 'BookHeaders.para.style',
    'booktitles': 'BookTitle.para.style',
    'bookintroduction': 'BookIntroduction.para.style',
    'bookintroductionendtitles': 'BookIntroductionEndTitles.para.style',
    'para': 'Para.para.style',
    'section': 'Section.para.style',
    'list': 'List.para.style',
    'cellalign': 'Cell.align',
    'introchar': 'IntroChar.char.style',
    'char': 'Char.char.style',
    'listchar': 'ListChar.char.style',
    'ms': 'Milestone',
    'footnotechar': 'FootnoteChar.char.style',
    'crossrefchar': 'CrossReferenceChar.char.style',
}

