= tr
:description: Table row
:url-repo: https://github.com/usfm-bible/tcdocs/blob/main/markers/para/.adoc
:noindex:
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

// tag::public[]

== Summary

Description:: Table row start.
[NOTE]
.Syntax notes
====
In *USFM*, a table is composed by a series of paragraphs marked with `\tr`. In *USX* the sequence of `\tr` rows is composed within a `+<table>...</table>+` container. See xref:para:tables/index.adoc[Tables].
====
Syntax::
* *USFM:* `+\tr_{content}+`
* *USX:* `+<table><row style="tr" vid="{vid}">{content}</row>...</table>+`
`vid`::: Required to re-identify the current verse whenever the previous xref:para:index.adoc[paragraph] or xref:para:tables/index.adoc[table] closed prior the end of the current verse text. A standard book + chapter + verse scripture reference. Book names must be a standard 3-character xref:para:identification/books.adoc[book identifier]. Chapter:verse separator is always a colon `:`.
*** Pattern: `+[A-Z1-4]{3} ?[a-z0-9\-:]*+`
`content`::: xref:char:tables/index.adoc[Character Types for Tables].
// tag::spec[]
Added:: 1.0
// end::spec[]

== Examples

See the examples provided in the xref:char:tables/index.adoc[character/cell types for table rows] descriptions.

== Properties

StyleType:: xref:para:index.adoc[Paragraph]
OccursUnder:: `[BookIntroductionContent]`, `[ChapterContent]`, `[SidebarContent]`, `[PeripheralContent]`
TextType:: VerseText
TextProperties:: paragraph, publishable, vernacular

== Publication Issues

// end::public[]

== Discussion
