= Normalizing Output
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

## Whitespace

[#significant-whitespace]
### Significant Whitespace

Significant whitespace is a critical part of a USFM document and should be preserved.

* The xref:ROOT:glossary.adoc[whitespace (`WS`)] after the end of a xref:para:index.adoc[paragraph] marker, or the end of the opening marker within a xref:char:index.adoc[character] or xref:note:index.adoc[note] marker pair.
* The xref:ROOT:glossary.adoc[newline (`NL`)] preceding a new paragraph marker.

_See also:_ xref:ROOT:glossary.adoc[Glossary]

[#reducing-whitespace]
### Reducing Whitespace

USFM/USX adopts the following principles for reducing whitespace. Reducing whitespace means changing multiple whitespace into a single whitespace.

* Whitespace around a xref:ROOT:glossary.adoc[newline (`NL`)] is reduced.
* Whitespace within text (e.g. between words) is not reduced.
* Whitespace around text (e.g. between paragraphs) is reduced.
* Whitespace before xref:cv:v.adoc[verses] is reduced. A space is not required before xref:cv:v.adoc[verses] (example: a parenthesised verse number like (3)).
* Applications and processors may offer the user the option to reduce whitespace within text.

[NOTE]
====
USX documents contain whitespace that delimits aspects of the XML syntax itself. XML also allows for unlimited whitespace wherever it is permitted in the XML syntax, typically applied for the purpose of formatting for easier reading ('pretty-printing').
====

=== Handling special contexts

Reducing whitespace can result in whitespace remaining in the text which may be considered insignificant, depending on its context.

For example, the space preceding the footnote in:

[source#src-wsn_3,usfm]
----
\v 27 Can any of you live a bit longer \f + \fr 6.27: \fq live a bit longer;
----

could be removed:

[source#src-wsn_4,usfm]
----
\v 27 Can any of you live a bit longer\f + \fr 6.27: \fq live a bit longer;
----

And a space after a cross reference occurring at the start of a verse:

[source#src-wsn_5,usfm]
----
v 7 \x - \xo 2.7: \xt 1 Co 15.45.\x* Then the \nd Lord\nd* God took some soil
from the ground and formed a man
----

could be removed:

[source#src-wsn_6,usfm]
----
v 7 \x - \xo 2.7: \xt 1 Co 15.45.\x*Then the \nd Lord\nd* God took some soil
from the ground and formed a man
----

However, a normalization process cannot _generally_ remove ALL whitespace preceding and following note marker pairs. In many cases a single whitespace is expected between the texts which precede and follows a note.

[TIP]
====
* Validation tools may flag suspicious whitespace.
* Editors and processors can takes steps to discourage ambiguous whitespace wherever possible.
* Normalization tools can identify and handles special contexts.
* Publication tools and other post processors can identify and handle special contexts in the manner which is most suitable for the intended output.
====

== Newlines

All xref:para:index.adoc[paragraph] markers should be preceded by a single newline.

As a recommended best practice for USFM editors, inline markup (xref:char:index.adoc[character-level markup], xref:note:footnote/index.adoc[footnotes], or xref:note:crossref/index.adoc[cross references]) should not be preceded by a newline. It would be acceptable for a <<reducing-whitespace,whitespace reducing>> process to replace a newline and preceding whitespace (i.e. multiple spaces) before this inline markup with a single space, but it should not remove all whitespace.

In the following example, the footnote `+\f ...\f*+` at Matthew 6:27:

[source#src-wsn_1,usfm]
----
\v 27 Can any of you live a bit longer
\f + \fr 6.27: \fq live a bit longer; \ft or \fq grow a bit taller.\f* by 
worrying about it?
----

would be normalized as:

[source#src-wsn_2,usfm]
----
\v 27 Can any of you live a bit longer \f + \fr 6.27: \fq live a bit 
longer; \ft or \fq grow a bit taller.\f* by worrying about it?
----
