= General Markup Syntax
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

There are five general categories of USFM/USX markup:

* xref:cv:index.adoc[Chapters and Verses]
* xref:para:index.adoc[Paragraphs]
* xref:char:index.adoc[Characters]
* xref:note:index.adoc[Notes]
* xref:ms:index.adoc[Milestones]

== USFM

In *USFM*, all markers begin with a backslash character `\`.

* xref:para:index.adoc[Paragraph] markers, and the opening marker for xref:char:index.adoc[characters] and xref:note:index.adoc[notes] are followed by a space. Example: ``++\p ++``.
* xref:char:index.adoc[Character] markers occur in pairs, marking a span of text within a paragraph. The closing marker is identical to the opening marker, terminated with an asterisk character `+*+`. Example: `+\w grace\w*+`.
* xref:note:index.adoc[Note] markers also occur in pairs, marking the start and end of the xref:note:footnote/index.adoc[footnote] or xref:note:crossref/index.adoc[cross reference] content.
* xref:ms:index.adoc[Milestone] markers follow a syntax similar to xref:char:index.adoc[character markers], but using a self-closing syntax which immediately terminates the marker with a second backslash plus asterisk `\*`. Example: `+\\qt-s\*+`
* xref:cv:c.adoc[Chapters] and xref:cv:v.adoc[verses] are unique elements. Their syntax is similar to a paragraph marker. The chapter or verse number itself is added after the marker and its space. Chapter and verses are also like milestones because they identify the location for the start of a chapter or verse. In USFM there is no marker to indicate the end of a chapter or verse.

== USX

*USX* follows the https://www.w3.org/TR/xml/[standard syntax] for XML documents.

* xref:para:index.adoc[Paragraphs] occur within a `+<para>+` element.
* xref:char:index.adoc[Character] spans occur within a `+<char>+` element.
* xref:note:index.adoc[Notes] occur within a `+<note>+` element.
* xref:ms:index.adoc[Milestones] occur as an `+<ms/>+` element.
* xref:cv:c.adoc[Chapters] and xref:cv:v.adoc[verses] occur as 'milestone-like' self-closing `+<chapter/>+` or `+<verse/>+` elements which identify the start for a chapter or verse. Optionally, `+<chapter/>+` and `+<verse/>+` elements can be added to mark the end of a chapter or verse by using the `+eid+` attribute instead of the `+sid+` attribute. The end elements should be placed at the end of the Scripture text for chapter or verse.

Different _types_ of paragraph, character, note, or milestones are identified by a `+style+` attribute. The `+style+` attribute is the value which associates the element with its corresponding USFM marker.

== Numbered Markers/Styles
Some markers or styles include an optional numeric variable, which is represented in this documentation by a hash character `+#+`. The number indicates:

* A portion of a larger text, or relative weighting of the components of the text, such as `mt1`, `mt2`, `mt3` which are parts of a xref:para:titles-sections/mt.adoc[main title].
* The level of a division or section (hierarchy).
* The level of indentation relative to other like elements, as in poetry (xref:para:poetry/q.adoc[q#]) or lists (xref:para:lists/li.adoc[li#]) or outlines (xref:para:introductions/io.adoc[io#]).

*marker = marker1* — The _unnumbered_ version of a marker or style should only be used when one level of this marker exists within the text (only). _Numbered_ markers should always be used when more than one level of the marker exists within the text.

[CAUTION]
====
A specific numbered marker or style should not be used to indicate a specific occurrence of the element type (i.e. you should not use `s3` to represent the the particular section heading occuring before the "Story of Creation" in Genesis 1.)
====

== USFM Endmarkers in Footnotes and Cross References

Elements which make up xref:note:footnote/index.adoc[footnote] or xref:note:crossref/index.adoc[cross reference] content are xref:char:index.adoc[character] level markers, which means that they are defined with a start and end marker. The majority of scripture translation projects working with USFM have followed a syntax for editing footnotes or cross references which does not require the explicit end marker. This was done in order to reduces the amount of markup within the notes text, making it easier to read.

Examples of the two markup approaches for notes are given below. Both of these are syntactically acceptable in USFM.

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fk Issac: \ft In Hebrew means "laughter"\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fk Issac: \fk*\ft In Hebrew means "laughter"\ft*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fk">Issac: </char>
  <char style="ft">In Hebrew means "laughter"</char>
</note>
----
======

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fr 1.14 \fq religious festivals; \ft or \fqa seasons.\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fr 1.14 \fr*\fq religious festivals; \fq*\ft or \ft*\fqa seasons.\fqa*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fr">1.14 </char>
  <char style="fq">religious festivals; </char>
  <char style="ft">or </char>
  <char style="fqa">seasons.</char>
</note>
----
======

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fr 2.4 \fk The \+nd Lord\+nd*: \ft See \+nd Lord\+nd* in Word List.\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fr 2.4 \fr*\fk The \+nd Lord\+nd*: \fk*\ft See \+nd Lord\+nd* in 
Word List.\ft*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fr">2.4 </char>
  <char style="fk">The <char style="nd">Lord</char>: </char>
  <char style="ft">See <char style="nd">Lord</char> in Word List.</char>
</note>
----
======

[NOTE]
====
xref:char:nesting.adoc[Nested] character markers within notes _always_ require explicit opening and closing markers.
====