= Syntax Notes
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

_See also:_

* xref:whitespace.adoc[Whitespace]
* xref:extensions.adoc[Extensions]
* xref:syntax-docs.adoc[Docs Syntax Notes]

== General Syntax (USFM)

* There are three broad categories of USFM markup - xref:para:index.adoc[paragraph], xref:char:index.adoc[character], and xref:note:index.adoc[note] types.
* All USFM markers begin with a backslash character `\`.
* xref:para:index.adoc[Paragraph] markers, and the opening marker for xref:char:index.adoc[characters] and xref:note:index.adoc[notes] are followed by whitespace.
* xref:char:index.adoc[Character] markers occur in pairs, marking a span of text within a paragraph.
** The closing marker character is the same as the opening marker, but ends with an asterisk character `+*+`. Example: `+\w grace\w*+`.
* xref:note:index.adoc[Note] markers also occur in pairs, marking the start and end of the xref:note:footnote/index.adoc[footnote] or xref:note:crossref/index.adoc[cross reference] content.

== Numbered Markers
Some USFM markers include an optional numeric variable, which is represented in this documentation by a hash character `#`. In USFM the number indicates:
* A portion of a complete element, or relative weighting of the "pieces" of the elements, such as `\mt1`, `\mt2`, `\mt3` which are parts of a major title.
* The level of the division or section (hierarchy).
* The level of indentation relative to other like elements, as in poetry (xref:para:poetry/q.adoc[\q#]) or lists (xref:para:lists/li.adoc[\li#]) or outlines (\io#).

*marker = marker1* — The _unnumbered_ version of a marker should only be used when only one level of this marker exists within the text. _Numbered_ markers should always be used when more than one level of the marker exists within the text.

[CAUTION]
====
A specific numbered marker should not be used to indicate a specific occurrence of the element type (e.g. you should not use `\s3` to represent the the particular section heading occuring before the "Story of Creation" in Genesis 1.)
====

== Endmarkers in Footnotes and Cross References

Elements which make up xref:note:footnote/index.adoc[footnote] or xref:note:crossref/index.adoc[cross reference] content are xref:char:index.adoc[character] level markers, which means that they define a start and end marker. Some USFM editors interpret the presence of a new character marker as an implicit closure of any preceding character level marker. The majority of scripture translation projects working with USFM have followed this syntax for footnotes or cross references (not supplying the explicit end marker) since this reduces the amount of markup within the notes text, making it easier to read as a result.

Examples of the two markup approaches for notes is provided below:

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fk Issac: \ft In Hebrew means "laughter"\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fk Issac: \fk*\ft In Hebrew means "laughter"\ft*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fk">Issac: </char>
  <char style="ft">In Hebrew means "laughter"</char>
</note>
----
======

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fr 1.14 \fq religious festivals; \ft or \fqa seasons.\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fr 1.14 \fr*\fq religious festivals; \fq*\ft or \ft*\fqa seasons.\fqa*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fr">1.14 </char>
  <char style="fq">religious festivals; </char>
  <char style="ft">or </char>
  <char style="fqa">seasons.</char>
</note>
----
======

[tabs]
======
USFM (implicit closure)::
+
[source,usfm]
----
\f + \fr 2.4 \fk The \+nd Lord\+nd*: \ft See \+nd Lord\+nd* in Word List.\f*
----
USFM (explicit closure)::
+
[source,usfm]
----
\f + \fr 2.4 \fr*\fk The \+nd Lord\+nd*: \fk*\ft See \+nd Lord\+nd* in 
Word List.\ft*\f*
----
USX::
+
[source,xml]
----
<note caller="+" style="f">
  <char style="fr">2.4 </char>
  <char style="fk">The <char style="nd">Lord</char>: </char>
  <char style="ft">See <char style="nd">Lord</char> in Word List.</char>
</note>
----
======

[NOTE]
====
xref:char:nesting.adoc[Nested] character markers within notes _always_ require explicit opening and closing markers, and must use the syntax for xref:char:nesting.adoc[character marker nesting].
====