= Syntax Notes
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

_See also:_

* xref:whitespace.adoc[Whitespace]
* xref:extensions.adoc[Extensions]
* xref:syntax-docs.adoc[Docs Syntax Notes]

== General Syntax (USFM)

* There are three broad categories of USFM markup - xref:para:index.adoc[paragraph], xref:char:index.adoc[character], and xref:note:index.adoc[note] types.
* All USFM markers begin with a backslash character `\`.
* xref:para:index.adoc[Paragraph] markers end with the next space character.
* xref:char:index.adoc[Character] markers occur in pairs, marking a span of text within a paragraph.
* xref:note:index.adoc[Note] markers also occur in pairs, marking the start and end of the footnote, cross reference, or study note content.
* For marker pairs (character and note), the opening marker ends with the next space character (as with paragraph markers). The matching closing marker is identical to the opening marker but ends with an asterisk character `+*+`. Example: `+\w grace\w*+`.

== Numbered Markers
Some USFM markers include an optional numeric variable, which is represented in this documentation by a hash character `#`. In USFM the number indicates:
* A portion of a complete element, or relative weighting of the "pieces" of the elements, such as `\mt1`, `\mt2`, `\mt3` which are parts of a major title.
* The level of the division or section (hierarchy).
* The level of indentation relative to other like elements, as in poetry (xref:para:poetry/q.adoc[\q#]) or lists (xref:para:lists/li.adoc[\li#]) or outlines (\io#).

*marker = marker1* — The _unnumbered_ version of a marker should only be used when only one level of this marker exists within the text. _Numbered_ markers should always be used when more than one level of the marker exists within the text.

[CAUTION]
====
A specific numbered marker should not be used to indicate a specific occurrence of the element type (e.g. you should not use `\s3` to represent the the particular section heading occuring before the "Story of Creation" in Genesis 1.)
====

== Endmarkers in Footnotes and Cross References
The boundaries of footnote or cross reference text are defined by an opening and closing marker, as in the following footnote syntax example:

[source#src-noteSyntax_1,usfm]
----
\f_+_(\fr_REF_)footnote content\f*
----

Elements which make up the footnote or cross reference content are character level markers, which means that they each define a start and a end marker. Some USFM editors interpret the presence of a new character marker as an implicit closure of any preceding character level marker. As a result, most scripture translation projects working with USFM have adopted the approach of authoring footnotes or cross references without supplying the explicit end marker, since this reduces the amount of markup within the notes, and is somewhat easier to read and interpret.

Examples of the two markup approaches for notes is provided below:

====
[source,usfm]
.Implicit closure
----
`+\f + \fk Issac: \ft In Hebrew means "laughter"\f*+`
----
[source,usfm]
.Explicit end marker
----
`+\f + \fk Issac:\fk* \ft In Hebrew means "laughter"\ft*\f*+`
----
====

====
[source,usfm]
.Immplicit closure
----
\f + \fr 1.14 \fq religious festivals; \ft or \fqa seasons.\f*
----
[source,usfm]
.Explicit end marker
----
\f + \fr 1.14\fr* \fq religious festivals;\fq* or \fqa seasons.\fqa*\f*
----
====

====
[source,usfm]
.Implicit closure
----
\f + \fr 2.4 \fk The \+nd Lord\+nd*: \ft See \+nd Lord\+nd* in 
Word List.\f*
----
[source,usfm]
.Explicit end marker
----
\f + \fr 2.4\fr* \fk The \+nd Lord\+nd*:\fk* \ft See \+nd Lord\+nd* in 
Word List.\ft*\f*
----
====

[NOTE]
====
xref:char:nesting.adoc[Nested] character markers within notes _always_ require explicit opening and closing markers, and must use the syntax for xref:char:nesting.adoc[character marker nesting].
====