= Whitespace
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

[#ws-definition]
== Definition

In USFM/USX, a 'common whitespace' (*_WS_*) character is xref:ROOT:glossary.adoc[defined] by the pattern ``++/(?:++``#$\{ws\}#``++|++``#$\{nl\}#``++|$)/++``, where:

ws:: ``++/[\u0009\u000D\u000A\u0020]/++``
** A single whitespace character.
nl:: ``++/(?:\u000D?\u000A|\u000D)/++``
** A single newline (as supported by all operating systems).

Common whitespace is found throughout the document _#content#_ for most languages.

_Some_ common whitespace in USFM/USX documents is 'structural whitespace'. Structural (_non-content_) whitespace exists either to aid in the readability of a source file, or to delimit markers. Structural whitespace is identified in the documentation's syntax diagrams (`WS`/`Ws`/`HS`/`Hs`) and is not part of the document _#content#_.

All other characters are always treated as _#content#_ (including other https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%3Awhitespace%3A&g=Lb&i[Unicode whitespace,window=_blank] characters).

[#ws-reducing]
== Reducing or Eliminating Common Whitespace

* Any common whitespace is *reduced* according to these rules:

** Any string of *_WS_* chars which includes a newline is reduced to a single newline.
** Any string of *_WS_* chars which does not include a newline is reduced to a single space.

* Common whitespace can be *eliminated* when it occurs:

** At the start of any element's _#content#_.
** At the end of any element's _#content#_, except inside a xref:char:index.adoc[character] element, when followed by text or another xref:char:index.adoc[character] element.

* Common whitespace *canonicalization* is done as follows:

** A newline before a xref:char:index.adoc[character] marker is converted to a space. That space is _#content#_.
** Any whitespace before a xref:para:index.adoc[paragraph] marker, including none, is replaced by a newline. This newline is not _#content#_.

[NOTE]
====
USX documents contain common whitespace that delimits aspects of the XML syntax itself. XML allows for unlimited whitespace wherever it is permitted by the XML syntax, which is typically added for the purpose of formatting for easier reading (i.e. 'pretty-printing').
====
