#!/usr/bin/env python3

import lxml.etree as et
import lxml.isoschematron as sch
import argparse, re

def fn_matches(context, txt, reg):
    #print(f"{context=}, {txt=}, {reg=}")
    return re.match(reg, txt[0]) is not None

parser = argparse.ArgumentParser()
parser.add_argument("infile", help="Input USX file")
parser.add_argument("-t","--test",help="Schematron file")
parser.add_argument("-x","--xslt",action="store_true",help="Output generated xslt")
args = parser.parse_args()

nsf = et.FunctionNamespace("http://tcdocs.bible/re")
nsf['test'] = fn_matches
schema = sch.Schematron(file=args.test, store_xslt=args.xslt, compile_params={'allow-foreign': 'true'})
if args.xslt:
    print(schema.validator_xslt)
doc = et.parse(args.infile)
schema(doc)

