#!/usr/bin/env python3

import sys, os
try:
    from usfmtc.rnc2rng import parser, serializer
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'lib'))
    sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'lib', 'usfmtc'))
    from usfmtc.rnc2rng import parser, serializer

def main():

    args = sys.argv[1:]
    input = open(args[0]) if len(args) > 0 else sys.stdin
    try:
        xml = serializer.XMLSerializer().toxml(parser.parse(f=input))
    except parser.ParseError as e:
        print('parse error ' + e.msg)
        sys.exit(1)

    if len(args) > 1:
        open(sys.argv[2], 'w').write(xml + '\n')
    else:
        print(xml)

if __name__ == '__main__':
    main()
