#!/usr/bin/env python3

import os, sys

try:
    from usfmtc import main
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'lib'))
    from usfmtc import main

from gooey import Gooey

Gooey(main)()
