#!/usr/bin/env python3

import argparse, os, sys, logging

try:
    from usfmtc import USX, usfmGrammar, _grammarDoc
except ImportError:
    sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'lib'))
    from usfmtc import USX, usfmGrammar, _grammarDoc

from gooey import Gooey

Gooey(main)()
