= vid
:description: Current reference identifier
:url-repo: https://github.com/usfm-bible/tcdocs/blob/main/markers/ms/vid.adoc
:noindex:
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

// tag::public[]

== Summary

Description:: Current reference identifier. For indicating what the current reference is within a fragment of scripture (e.g. a scripture module), and to provide the current header text (xref:para:identification/h.adoc[h]). This can be used instead of inserting a xref:cv:c.adoc[c] and xref:cv:v.adoc[v] marker in the text fragment.
[NOTE]
.Syntax notes
====
In *USFM* `++\vid\*++` is presented as a xref:ms:index.adoc[milestone]. In **USX** the attribute values from this milestone are expressed within the following xref:para:index.adoc[paragraph] element as #__@h__# and #__@vid__#, rather than by the addition of an `<ms/>` element.
====
xref:ROOT:syntax-docs.adoc#_syntax[Syntax image:ROOT:help.svg[]]::
* *USFM:* ``++\vid|++``#__@h @ref__#``++\*++``
* *USX:* ``++<para style="++``#__style__#``++" h="++``#__@h__#``++" vid="++``#__@ref__#``++">++``#__content__#``++</para>++``
#ref*#::: Use for identifying the current scripture reference. _(default attribute)_
** Follows the pattern: `+[A-Z1-4]{3}(-[A-Z1-4]{3})? ?[a-z0-9\-:]*+`.
** Example: `MAT 3:1-4`, where:
*** Book names is a standard 3-character scripture xref:doc:books.adoc[book identifier].
*** The chapter + verse separator is a colon `:`.
*** Verse ranges are indicated using a hyphen.
#h#::: Running header text.
Style Type:: xref:ms:index.adoc[Milestone]
Valid In:: `[xref:doc:index.adoc#doc-book-chapter-content[ChapterContent]]`
// tag::spec[]
Added:: 3.1.2 (TC proposal: https://github.com/usfm-bible/tcdocs/blob/main/proposals/2025/U25008%20vid.md[U25008^])
// end::spec[]

== Examples

[tabs]
======
USFM::
+
.Mark 4.26-28 (BSB)
[source#src-usfm-ms-vid_1,usfm,highlight=2]
----
\id MRK Fragment MRK 4:26-28
\vid|h="Mark" ref="MRK 4:26"\*
\s1 The Seed Growing Secretly
\p \v 26 Jesus also said, “The kingdom of God is like a man who scatters seed on 
the ground.
\v 27 Night and day he sleeps and wakes, and the seed sprouts and grows, though 
he knows not how.
\v 28 All by itself the earth produces a crop—first the stalk, then the head, 
then grain that ripens within.
----
USX::
+
.Mark 4.26-28 (BSB)
[source#src-usx-ms-vid_1,xml,highlight=2]
----
<usx version="3.1.2">
  <para style="s1" h="Mark" vid="MRK 4:26">The Seed Growing Secretly</para>
  <para style="p"><verse style="v" number="26" />Jesus also said, “The kingdom 
  of God is like a man who scatters seed on the ground.
  <verse style="v" number="27" />Night and day he sleeps and wakes, and the seed 
  sprouts and grows, though he knows not how.
  <verse style="v" number="28" />All by itself the earth produces a crop—first 
  the stalk, then the head, then grain that ripens within.</para>
</usx>
----
======

== Properties

StyleType:: xref:ms:index.adoc[Milestone]
OccursUnder:: `[ChapterContent]`

== Publication Issues

// end::public[]

== Discussion

Links to open repository Issues