= vid
:description: Current reference and header field milestone
:url-repo: https://github.com/usfm-bible/tcdocs/blob/main/markers/ms/vid.adoc
:noindex:
ifndef::localdir[]
:source-highlighter: rouge
:localdir: ../
endif::[]
:imagesdir: {localdir}/images

// tag::public[]

== Summary

Description:: Current reference and header field milestone. Recommended for use in a module or scripture text fragment to avoid the need to include xref:cv:c.adoc[c] or xref:cv:v.adoc[v] markers which may not be required for publication.
xref:ROOT:syntax-docs.adoc#_syntax[Syntax image:ROOT:help.svg[]]::
* *USFM:* ``++\vid |++``#__@ref @h__#``++\*++``
* *USX:* ``++<ms style="vid" ++``#__@ref @h__#``++/>++``
#ref# *::: The current scripture reference. _(default attribute)_
** Follows the pattern: `+[A-Z1-4]{3}(-[A-Z1-4]{3})? ?[a-z0-9\-:]*+`.
** Example: `MRK 4:26`, where:
*** Book names is a standard 3-character scripture xref:doc:books.adoc[book identifier].
*** The chapter + verse separator is a colon `:`.
*** Verse ranges are indicated using a hyphen.
#h#::: The current running head (xref:para:identification/h.adoc[h]) field..
Style Type:: xref:ms:index.adoc[Milestone]
Valid In:: `[xref:doc:index.adoc#doc-book-chapter-content[ChapterContent]]`
// tag::spec[]
Added:: 3.2
// end::spec[]

== Examples

[tabs]
======
USFM::
+
.Mark 4.26 (BSB)
[source#src-usfm-ms-vid_1,usfm,highlight=2]
----
\id MRK Fragment MRK 4:26-28
\vid|h="Mark" ref="MRK 4:26"\*
\s1 The Seed Growing Secretly
\p \v 26 Jesus also said, “The kingdom of God is like a man who scatters seed 
on the ground.
\v 27 Night and day he sleeps and wakes, and the seed sprouts and grows, though 
he knows not how.
\v 28 All by itself the earth produces a crop—first the stalk, then the head, 
then grain that ripens within.
\v 29 And as soon as the grain is ripe, he swings the sickle, because the harvest 
has come.\f + \fr 4:29 \ft See \xt Joel 3:13,\xt* including LXX.\f*”
----
USX::
+
.Mark 4.26 (BSB)
[source#src-usx-ms-vid_1,xml,highlight=3]
----
<?xml version="1.0" encoding="utf-8"?>
<usx version="3.2">
<para style="s1" h="Mark" vid="MRK 4:26">The Seed Growing Secretly</para>
<para style="p"><verse style="v" number="26" />Jesus also said, “The kingdom of 
God is like a man who scatters seed on the ground.
<verse style="v" number="27" />Night and day he sleeps and wakes, and the seed 
sprouts and grows, though he knows not how.
<verse style="v" number="28" />All by itself the earth produces a crop—first 
the stalk, then the head, then grain that ripens within.
</para></usx>
----
USJ::
+
.Mark 4.26 (BSB)
[source#src-usj-ms-vid_1,json,highlight=]
----
Missing
----
======

== Properties

== Publication Issues

// end::public[]

== Discussion
