= Character Level Attributes

USFM and USX 3 provide a syntax for adding named attributes to character markers. Attributes define additional properties for the marked content, and are a means of extending the meta-information contained within in a text. USFM _formally_ defines attributes for a <<chars-with-attrib,selected set>> of current xref:char:index.adoc[character] types.

== General Syntax

*In USFM*, within a character marker span an attributes list is separated from the text content by a vertical bar `|`. Attributes are listed as pairs of name + corresponding value using the syntax: `attribute="value"`. The attribute name is a single ASCII string. The value is wrapped in quotes.

*In USX*, attributes are applied to elements in the standard XML syntax: `attribute="value"`.

[tabs]
======
USFM::
+
.Glossary word with `lemma` attribute
[source#src-usfm-char-w-attrib,usfm]
----
\w gracious|lemma="grace"\w*
----
USX::
+
.Glossary word with `lemma` attribute
[source#src-usx-char-w-attrib_1,xml]
----
<char style="w" lemma="grace">gracious</char>
----
USJ::
+
.Glossary word with `lemma` attribute
[source#src-usj-char-w-attrib_1,json]
----
{
  "type": "char",
  "marker": "w",
  "lemma": "grace",
  "content": ["gracious"]
}
----
======

[NOTE]
====
Nearly all USX elements contain a required `style` attribute. For xref:para:index.adoc[<para>] and xref:char:index.adoc[<char>] elements, the `style` attribute defines the xref:para:index.adoc[paragraph] or xref:char:index.adoc[character] type.
====

== Default Attribute

*In USFM*, when content is supplied in the position of an attribute, but without an explicit attribute name, the specification defines a single default. This allows a commonly used attribute (the default) to be added with as little additional markup in the text as possible.

The concept of a "default attribute" is only valid in USFM. *In USX*, attributes always need to be expressed fully as `attribute="value"` together.

[tabs]
======
USFM::
+
.Glossary word with un-named default `lemma` attribute
[source#src-usfm-char-w-attrib-default,usfm]
----
\w gracious|grace\w*
----
USX::
+
.USX: Glossary word with `lemma` attribute
[source#src-usx-char-w-attrib_2,xml]
----
<char style="w" lemma="grace">gracious</char>
----
USJ::
+
.USX: Glossary word with `lemma` attribute
[source#src-usj-char-w-attrib_2,json]
----
{
  "type": "char",
  "marker": "w",
  "lemma": "grace",
  "content": ["gracious"]
}
----
======

== Multiple Attribute Values

In cases where more than one value is needed for an attribute key, use a comma separated list within the value string. Whitespace adjacent to the comma separators is ignored.

[tabs]
======
USFM::
+
.Glossary word with multiple `strong` values
[source#src-usfm-char-w-attrib-strong,usfm]
----
\w gracious|strong="H1234,G5485"\w*
----
USX::
+
.Glossary word with multiple `strong` values
[source#src-usx-char-w-attrib-strong,xml]
----
<char style="w" strong="H1234,G5485">gracious</char>
----
USJ::
+
.Glossary word with multiple `strong` values
[source#src-usj-char-w-attrib-strong,json]
----
{
  "type": "char",
  "marker": "w",
  "strong": "H1234,G5485",
  "content": ["gracious"]
}
----
======

See the attributes for xref:char:features/w.adoc[wordlist/glossary entry] for other examples.

== Multiple Attribute Parts

In cases where an attribute value is composed of multiple parts (e.g. a compound word or phrase), separate the parts using a colon `:` within the value string.

See the `gloss` attribute for xref:char:features/w.adoc[ruby glosses] for an example of the use of this syntax.

== Backward Compatibility

Pre-existing markers which formally provide attributes in USFM/USX 3 (or newer) may continue to be used without attributes. `+\w gracious\w*+` (no attributes) and `+<char style="w">gracious</char>+` remain valid.

== User Defined Attributes

Using the general syntax above, attributes may be added to any character markers beyond the formalized set in the current version of the USFM/USX specification. These will not be considered canonical, and software supporting USFM/USX is not required to process user-defined attributes.

User defined attributes must begin with the prefix `+x-+`.

[tabs]
======
USFM::
+
.Glossary word with user defined attribute
[source#src-usfm-char-w-attrib-user,usfm]
----
\w gracious|x-myattr="value"\w*

\w gracious|lemma="grace" x-myattr="value"\w*
----
USX::
+
.Glossary word with user defined attribute
[source#src-usx-char-w-attrib-user,xml]
----
<char style="w" x-myattr="value">gracious</char>

<char style="w" lemma="grace" x-myattr="value">gracious</char>
----
USJ::
+
.Glossary word with user defined attribute
[source#src-usj-char-w-attrib-user,json]
----
{
  "type": "char",
  "marker": "w",
  "x-myattr": "value",
  "content": ["gracious"]
}

{
  "type": "char",
  "marker": "w",
  "lemma": "grace",
  "x-myattr": "value",
  "content": ["gracious"]
}
----
======

[#chars-with-attrib]
== Characters Types with Attributes

* xref:char:features/jmp.adoc[jmp - Link text] -- `href`, `title`, `id`
* xref:char:features/rb.adoc[rb - Ruby gloss] -- `gloss`
* xref:char:features/w.adoc[w - Wordlist entry] -- `lemma`, `strong`, `srcloc`
* xref:char:features/ref.adoc[ref - Scripture reference(s)] -- `loc`, `gen`
* xref:fig:fig.adoc[fig - Figure] -- `alt`, `src`, `size`, `loc`, `copy`, `ref`