= \w ...\w*
:description: Wordlist / glossary / dictionary entry
:url-repo: https://github.com/usfm-bible/tcdocs/blob/main/markers/char-w.adoc
:source-highlighter: pygments

== Summary

Description:: Wordlist / glossary / dictionary entry. Surround a word or phrase with this markup to indicate that it should appear in the glossary.
Syntax:: `+\w_...\w*+`
Attributes:: `lemma`, `strong`, `srcloc`
Added:: 1.0
Updated:: 3.0 (attributes)

== Properties

StyleType:: Character
OccursUnder:: `ip im ipi imi ipq imq ipr iq iq1 iq2 iq3 io io1 io2 io3 io4 ms ms1 ms2 s s1 s2 s3 s4 cd sp d lh li li1 li2 li3 li4 lf lim lim1 lim2 lim3 lim4 m mi nb p pc ph phi pi pi1 pi2 pi3 pr pmo pm pmc pmr po q q1 q2 q3 q4 qc qr qd qm qm1 qm2 qm3 tr th1 th2 th3 th4 thr1 thr2 thr3 thr4 tc1 tc2 tc3 tc4 tcr1 tcr2 tcr3 tcr4 f fe ef erq esb x ex`
TextType:: VerseText
TextProperties:: publishable, vernacular

== Attributes

lemma:: Citation form for the term in the glossary _(default)_
strong:: Strong’s ID in the form `+H####+` (Hebrew) or `+G####+` (Greek)
- A strong’s ID augmentation identifier, if required, should be separated from the strong value by a colon `:`. An augmentation is a method of extending Strong’s by aligning it to another lexicon (e.g. Brown-Driver-Briggs). This requires dividing some words into two or more separate words.
- There are instances where more than one word may need to be included within `+\w_...\w*+` because of how Hebrew and Greek use word repetition - e.g. for a superlative. Exodus 29:37 repeats the word ‘holy’ as the superlative form.
srcloc:: Location of the word in the source text; Example: GNT version 5 text, book 51, chapter 1, verse 2, word 1.

== Structure

'Railroad' type diagram here...

== Examples

Source USFM text and corresponding formatted layout image

== Publication Issues

== Discussion

Links to open repository Issues